[package]
name = "quicap"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
env_logger = "0.11.8"
log = { version = "0.4", features = ["max_level_debug"] }
quiche = "0.24"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "io-util", "sync"] }
tokio-tun = "0.14"
